nelmio_api_doc:
  documentation:
    info:
      title: My App
      description: This is an awesome app!
      version: 1.0.0
      x-build: #CommitHash
    components:
      securitySchemes:
        Bearer:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - Bearer: []
    paths:
      /api/login:
        post:
          tags:
            - Security
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - username
                    - password
                  properties:
                    username:
                      type: string
                      description: The username of the user.
                    password:
                      type: string
                      description: The password of the user.
          responses:
            '200':
              description: Successful login
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      token:
                        type: string
                        description: The access token.
                      refreshToken:
                        type: string
                        description: The refresh token.
            '401':
              description: Unauthorized
      /api/refresh:
        post:
          summary: Refresh access token
          tags:
            - Security
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  required:
                    - refresh_token
                  properties:
                    refresh_token:
                      type: string
                      description: The refresh token.
          responses:
            '200':
              description: Successful refresh
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      token:
                        type: string
                        description: The access token.
                      refreshToken:
                        type: string
                        description: The refresh token.
            '401':
              description: Unauthorized
  areas:
    path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
      - ^/api(?!/doc$)
